//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Windows.Forms.Grid.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Windows.Forms.Grid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   이미 초기화가 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlreadyInitialized {
            get {
                return ResourceManager.GetString("AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변환 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제할 수 없는 항목입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRemove {
            get {
                return ResourceManager.GetString("CannotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CaptionRow_Text {
            get {
                return ResourceManager.GetString("CaptionRow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 소스 초기화에 실패했습니다. 데이터 소스가 IList, IListSource 또는 IBindingList 인터페이스를 구현하는 개체인지 확인하십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DataSourceInitializingFailed {
            get {
                return ResourceManager.GetString("DataSourceInitializingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefaultColumnName {
            get {
                return ResourceManager.GetString("DefaultColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tooltip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefaultTooltip {
            get {
                return ResourceManager.GetString("DefaultTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   그룹화 시킬 컬럼을 이쪽으로 드래그하여 옮기세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupPanel_Text {
            get {
                return ResourceManager.GetString("GroupPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   높이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap InsertionRow {
            get {
                object obj = ResourceManager.GetObject("InsertionRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap InsertionRowFocused {
            get {
                object obj = ResourceManager.GetObject("InsertionRowFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   GridEditingReasonType::Char 가 아닙니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidEditingReasonType_Char {
            get {
                return ResourceManager.GetString("InvalidEditingReasonType_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GridEditingReasonType::Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidEditingReasonType_Key {
            get {
                return ResourceManager.GetString("InvalidEditingReasonType_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GridEditingReasonType::Mouse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidEditingReasonType_Mouse {
            get {
                return ResourceManager.GetString("InvalidEditingReasonType_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽기 전용으로 되어 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행의 갯수가 0입니다. 먼저 Column을 추가하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoColumnException {
            get {
                return ResourceManager.GetString("NoColumnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Ntreev_Windows_Forms_Grid_ColumnPainter {
            get {
                object obj = ResourceManager.GetObject("Ntreev_Windows_Forms_Grid_ColumnPainter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] Ntreev_Windows_Forms_Grid_Cursors_Add {
            get {
                object obj = ResourceManager.GetObject("Ntreev_Windows_Forms_Grid_Cursors_Add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] Ntreev_Windows_Forms_Grid_Cursors_Movable {
            get {
                object obj = ResourceManager.GetObject("Ntreev_Windows_Forms_Grid_Cursors_Movable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] Ntreev_Windows_Forms_Grid_Cursors_Remove {
            get {
                object obj = ResourceManager.GetObject("Ntreev_Windows_Forms_Grid_Cursors_Remove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Ntreev_Windows_Forms_Grid_GridControl {
            get {
                object obj = ResourceManager.GetObject("Ntreev_Windows_Forms_Grid_GridControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   컬럼 정보를 가지고 있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NullColumn {
            get {
                return ResourceManager.GetString("NullColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InsertionRow는 삭제할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveInsertionRowException {
            get {
                return ResourceManager.GetString("RemoveInsertionRowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap RowEditing {
            get {
                object obj = ResourceManager.GetObject("RowEditing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap RowFocused {
            get {
                object obj = ResourceManager.GetObject("RowFocused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   값을 설정할 수 없습니다.\n Column::AutoValueConvert의 값이 false이거나, Column::TypeConverter에 의해서 변환될 수 있는 Type인지 확인하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetValueException {
            get {
                return ResourceManager.GetString("SetValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   넓이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
